language: python
script:
- echo "Start CI"
deploy:
  provider: script
  script:
  - bash deploy.sh
  skip_cleanup: true
  on:
    branch: master
before_install:
- openssl aes-256-cbc -K $encrypted_89c08c418c9a_key -iv $encrypted_89c08c418c9a_iv
  -in conf.yml.enc -out conf.yml -d
- openssl aes-256-cbc -K $encrypted_89c08c418c9a_key -iv $encrypted_89c08c418c9a_iv
  -in gcf-demo-2b39da7a07dd.json.enc -out gcf-demo-2b39da7a07dd.json -d
